name:                massaraksh
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/lagunoff/massaraksh
license:             BSD3
author:              Vladislav Lagunov
maintainer:          vlad.lagunoff@gmail.com
copyright:           2019 Vladislav Lagunov
category:            Web
extra-source-files:
- README.md

dependencies:
 - base >= 4.7 && < 5
 - aeson >= 1.4.0.0 && < 1.5.0.0
 - bytestring
 - text
 - lens
 - mtl
 - jsaddle
 - transformers

when:
  - condition: impl(ghcjs)
    then:
      ghc-options: -dedupe
      source-dirs: src-ghcjs
      dependencies:
        - ghcjs-base
    else:
      dependencies:
        - jsaddle-warp
      source-dirs: src-ghc

ghc-options: -Wall -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-matches -Wno-unused-do-bind -O0

library:
  source-dirs: src

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - BlockArguments
  - NamedFieldPuns
  - DuplicateRecordFields
  - DeriveGeneric
  - DeriveAnyClass
  - MultiParamTypeClasses
  - RecordWildCards
