resolver: lts-13.19

flags:
  massaraksh:
    examples: true

packages:
- .
- examples

extra-deps:
 - jsaddle-0.9.6.0
 - ref-tf-0.4.0.1
 - jsaddle-warp-0.9.6.0
 - jsaddle-dom-0.9.3.2
 - ghcjs-dom-jsaddle-0.9.4.0
 - polysemy-1.2.1.0
 - type-errors-0.2.0.0
 - type-errors-pretty-0.0.0.0
 - unagi-chan-0.4.1.2
 - th-abstraction-0.3.1.0
 - bifunctors-5.5.4
 - invariant-0.5.3
 - aeson-1.4.3.0
