name:                massaraksh-examples
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/lagunoff/massaraksh
license:             BSD3
author:              Vladislav Lagunov
maintainer:          vlad.lagunov@gmail.com
copyright:           2019 Vladislav Lagunov
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.4.0.0 && < 1.5.0.0
  - bytestring
  - text
  - lens
  - mtl
  - jsaddle
  - massaraksh

when:
  - condition: impl(ghcjs)
    then:
      ghc-options: -dedupe
      dependencies:
        - ghcjs-base
    else:
      dependencies:
        - jsaddle-warp

ghc-options: -Wall -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-matches -Wno-unused-do-bind -O0

executables:
  massaraksh-hello-world:
    source-dirs: hello-world
    main: Main.hs

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators
